// Route Paths
export const ENDPOINT = {
  PUBLIC: {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    // PRODUCTS: '/api/products?limit=5',
  },
  PRIVATE: {
    DASHBOARD: '/dashboard',
    PROFILE: '/profile',
    SETTINGS: '/settings',
  },
  NEWS: {
    LIST: '/api/news',
    CREATE: '/api/news',
    UPDATE: (id) => `/api/news/${id}`,
    DELETE: (id) => `/api/news/${id}`,
    DETAIL: (id) => `/api/news/${id}`,
  },
  AUTH: {
    LOGIN: '/api/auth/login',
    ME: '/api/auth/me',
    LOGOUT: '/api/auth/logout',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    REGISTER: '/api/auth/register',
    VERIFY_OTP: '/api/auth/verify-otp',
    RESET_PASSWORD: '/api/auth/reset-password',
    VERIFY_EMAIL: '/api/auth/verify-email',
    CHANGE_PASSWORD: '/api/auth/change-password',
  },
  USER: {
    UPDATE: (userId) => `/api/users/${userId}`,
    BILLING_ADDRESS: (userId) => `/api/users/${userId}/billing-address`,
    SHIPPING_ADDRESS: (userId) => `/api/users/${userId}/shipping-address`,
  },
  USERS: {
    LIST: '/api/users',
    PLAYERS: '/api/users/players',
    SPORT_PROVIDERS: '/api/users/sport-providers',
    SERVICE_PROVIDERS: '/api/users/service-providers',
    SUSPEND: (userId) => `/api/admin/users/${userId}/suspend`,
    UNSUSPEND: (userId) => `/api/admin/users/${userId}/unsuspend`,
    SUSPENDED_LIST: '/api/admin/suspended-users',
  },
  ADMIN: {
    DASHBOARD_STATS: '/api/admin/dashboard/stats',
    USER_TRENDS: '/api/admin/dashboard/user-trends',
    DEMAND_SUPPLY: '/api/admin/dashboard/demand-supply',
    HIGH_DEMAND_ALERTS: '/api/admin/dashboard/high-demand-alerts',
    TOP_LOCATIONS: '/api/admin/dashboard/top-locations',
    DASHBOARD_EXPORT: '/api/admin/dashboard/export',
    CONVERSION_FUNNEL: '/api/admin/dashboard/conversion-funnel',
    REGISTER_INTERESTS: '/api/admin/dashboard/register-interests',
    CONTACT_METADATA: '/api/admin/dashboard/contact-metadata',
  },
  SERVICES: {
    LIST: '/api/services',
    APPROVED: '/api/services?isApproved=true',
    PENDING: '/api/services?status=PENDING_APPROVAL',
    PROVIDER_SERVICES: (providerId) => `/api/services?providerId=${providerId}`,
    CREATE: '/api/services',
    DETAIL: (id) => `/api/services/${id}`,
    BOOKINGS: (id) => `/api/services/${id}/bookings`,
    BOOK: (id) => `/api/services/${id}/book`,
    INTERESTS: (id) => `/api/services/${id}/interests`,
    INTEREST: (id) => `/api/services/${id}/interest`,
    MESSAGES: (id) => `/api/services/${id}/messages`,
    ADMIN_BY_PROVIDER_ROLE: '/api/services/admin/by-provider-role',
    UPDATE: (id) => `/api/services/${id}`,
    DELETE: (id) => `/api/services/${id}`,
    APPROVE: (id) => `/api/services/${id}/approve`,
    REJECT: (id) => `/api/services/${id}/reject`,
    APPROVAL_STATUS: (id) => `/api/services/${id}/approval-status`,
  },
  EVENTS: {
    LIST: '/api/events',
    APPROVED: '/api/events?view=live',
    MY_LIST: '/api/events/my/list',
    ANALYTICS: '/api/events/analytics',
    CREATE: '/api/events',
    DETAIL: (id) => `/api/events/${id}`,
    UPDATE: (id) => `/api/events/${id}`,
    DELETE: (id) => `/api/events/${id}`,
    SAVE: (id) => `/api/events/${id}/save`,
    USER_SAVED: '/api/events/user/saved',
    FEATURE: (id) => `/api/events/${id}/feature`,
    ADMIN_FEATURE: (id) => `/api/admin/events/${id}/feature`,
    APPROVAL_STATUS: (id) => `/api/events/${id}/approval-status`,
    BAN: (id) => `/api/events/${id}/ban`,
  },
  COMMUNITY: {
    LIST_POSTS: '/api/community/posts',
    CREATE_POST: '/api/community/posts',
    POST_REACTION: (postId) => `/api/community/posts/${postId}/reactions`,
    MY_REACTION: (postId) => `/api/community/posts/${postId}/my-reaction`,
    COMMENTS: (postId) => `/api/community/posts/${postId}/comments`,
    MY_POSTS_ACTIVITY: '/api/community/my-posts/activity',
    MY_INTERACTIONS: '/api/community/my-interactions',
  },
  INTEREST_REQUESTS: {
    CREATE: '/api/interest-requests',
    ADMIN_ALL: '/api/interest-requests/admin/all',
  },
  INQUIRIES: {
    LIST: '/api/inquiries',
  },
};
