export const addListingDummyData = [
  {
    id: 'demo-1',
    title: 'Prioritize Your Mind, Transform Your Life',
    description: 'Discover tools, support, and guidance to nurture your mental well-being every day.',
    category: 'Mental Health',
    image: '/images/marketplace/image_1.jpg',
    providerName: 'Richmond Wellness',
    organizer: 'John Doe',
    about:
      'This physiotherapy service is designed specifically for women athletes who play sports like cricket, football, futsal and other physical games. It helps prevent injuries, improve performance, and support recovery so players can stay fit and confident.',
    overview: {
      clinicName: 'The Wellness Centre',
      addressLine1: '123 High Street',
      townCity: 'Richmond',
      postcode: 'TW9 1AB',
      primaryProfession: 'Physiotherapist',
      sessionType: 'In Clinic',
      sport: 'Football',
      professionalRegistration: 'HCPC Registered, CSP Member',
      insuranceInPlace: 'Yes',
    },
    bookings: [
      { name: 'Marvin McKinney', phone: '(319) 555-0115', email: 'willie.jennings@example.com' },
      { name: 'Eleanor Pena', phone: '(702) 555-0122', email: 'jessica.hanson@example.com' },
      { name: 'Jacob Jones', phone: '(302) 555-0107', email: 'alma.lawson@example.com' },
      { name: 'Annette Black', phone: '(604) 555-0102', email: 'nathan.roberts@example.com' },
      { name: 'Dianne Russell', phone: '(319) 555-0116', email: 'dolores.chambers@example.com' },
      { name: 'Albert Flores', phone: '(405) 555-0128', email: 'jackson.graham@example.com' },
    ],
    enquiries: [
      {
        playerName: 'Devon Lane',
        phone: '(405) 555-0128',
        email: 'jackson.graham@example.com',
        message:
          'Aloyan porta nisl dolor, molestie potenti neque elit mattis eu, feugiat elementum diam',
        date: '12 Mar 26',
      },
      {
        playerName: 'Marvin McKinney',
        phone: '(704) 555-0127',
        email: 'michael.mitc@example.com',
        message:
          'In a laoreet purus. Integer turpis quam, laoreet id orci nec, ultrices lacinia nunc. Aliquam erat',
        date: '12 Mar 26',
      },
    ],
  },
  {
    id: 'demo-2',
    title: 'Empowering Women Through Cricket',
    description: 'A safe and supportive cricket space for women to train, play, and grow.',
    category: 'Physios',
    image: '/images/marketplace/image_3.jpg',
    providerName: 'Empower Coaching',
    organizer: 'Jane Smith',
  },
  {
    id: 'demo-3',
    title: 'Fuel Your Body, Elevate Your Life',
    description: 'Science-backed nutrition plans to keep you healthy, energized, and thriving.',
    category: 'Nutrition',
    image: '/images/marketplace/image_4.jpg',
    providerName: 'Body Fuel Lab',
    organizer: 'Sarah Wilson',
  },
  {
    id: 'demo-4',
    title: 'Serving Confidence, Building Champions',
    description: 'A safe space for women to train, compete, and enjoy tennis together.',
    category: 'Wellbeing',
    image: '/images/marketplace/image_5.png',
    providerName: 'Ace Community',
    organizer: 'Emily Davis',
  },
  {
    id: 'demo-5',
    title: 'Play Tennis, Your Way',
    description: 'Connect with coaches, courts, and a supportive women-first tennis community.',
    category: 'Nutrition',
    image: '/images/Football.jpg',
    providerName: 'Racket Sisters',
    organizer: 'Maya Patel',
  },
  {
    id: 'demo-6',
    title: 'Women Performance Rehab Clinic',
    description: 'Recover faster with sports physio sessions designed around your schedule.',
    category: 'Physiotherapist',
    image: '/images/Support.jpg',
    providerName: 'Flow Recovery',
    organizer: 'Nora Clark',
  },
  {
    id: 'demo-7',
    title: "Women's Football Performance & Injury Prevention Camp",
    description: 'This specialized training and consultation program is designed exclusively for female football players.',
    category: 'Wellbeing',
    image: '/images/Discover.jpg',
    providerName: 'Peak Motion',
    organizer: 'Ava Martin',
  },
  {
    id: 'demo-8',
    title: 'Post-Match Recovery and Sports Massage Sessions',
    description: 'Targeted recovery plans to reduce soreness, prevent injury, and improve long-term athletic performance.',
    category: 'Sports Massage Therapist',
    image: '/images/Community.jpg',
    providerName: 'Recovery Studio',
    organizer: 'Isla Turner',
  },
  {
    id: 'demo-9',
    title: 'Strength and Conditioning for Emerging Women Athletes',
    description: 'Build explosive strength, confidence, and agility with structured weekly sessions.',
    category: 'Strength & Conditioning Coach',
    image: '/images/About.jpg',
    providerName: 'Athlete Lab',
    organizer: 'Zoe Green',
  },
];
